### ISSUE TITLE
Configurable unit values

### ISSUE THREAD

**Issue by leeMoonpig** [dragma/styled-bootstrap-grid#14]
Is it possible to to overwrite the default gutter and breakpoint values?

I'd like to be able to pass in my own configuration

**Comment by dragma** [comment]
Great idea. 
I'm rewriting this library atm. I'll include your request, donno yet if this will be part of the v1 or if I will drop a v0.2 with it before.
Stay tuned

**Comment by dragma** [comment]
Worked a bit on it today, published to npm the v0.2.0.
