### ISSUE TITLE
Feature Request: hiddenSm, hiddenXs

### ISSUE THREAD

**Issue by peterlazzarino** [dragma/styled-bootstrap-grid#18]
It would be great to be able to show / hide Col's based on screen size.

**Comment by checkonetwo** [comment]
yes!

**Comment by peterlazzarino** [comment]
I'm going to make a PR for this!

**Comment by dragma** [comment]
> I'm going to make a PR for this!

You can, but if you can't, i'll try to find some time tomorrow to do this.

**Comment by peterlazzarino** [comment]
It’s not a problem, I started on it today. Would like some feedback once
it’s ready

**Comment by peterlazzarino** [comment]
all set @dragma  #27
