### ISSUE TITLE
Missing support for styled-components v4

### ISSUE THREAD

**Issue by motiejunas** [dragma/styled-bootstrap-grid#22]
I cannot use styled-bootstrap-grid together with styled-components v4.

I am getting `TypeError: (0 , _styledComponents.injectGlobal) is not a function` error as `injectGlobal` was removed and replaced by createGlobalStyle in styled-components v4.

**Comment by peterlazzarino** [comment]
Added a PR #23

**Comment by dragma** [comment]
I have published a last styled-components-v3-compliant version, named 1.0.5.
I will work now on the v4 implementation based on your PR. Thanks for making it !

**Comment by dragma** [comment]
New package published !
Thanks !
