### ISSUE TITLE
GridThemeProvider does not work as expected

### ISSUE THREAD

**Issue by motiejunas** [dragma/styled-bootstrap-grid#24]
According to the documentation, I should provide theme like this:
```
<GridThemeProvider gridTheme={theme}>
```

It does not work in this way. It works only if I use `grittheme` instead of `gridTheme`. Some typo?

Another issue is that it does not work at all if I provide partly configuration. I need to provide full theme which is kind of annoying.

**Comment by dragma** [comment]
There is a typo you are absolutely right ! I'll fix this right now.

Can you open another issue with code example for the annoying thing ?
Thanks a lot.

**Comment by dragma** [comment]
New version published.
