### ISSUE TITLE
Container width depends on configuration

### ISSUE THREAD

**Issue by of-redkeds** [dragma/styled-bootstrap-grid#30]
Hi. Your grid have hard-coded styles 

```
${media.phone`
    max-width: 540px;
  `}

  ${media.tablet`
    max-width: 720px;
  `}

  ${media.desktop`
    max-width: 960px;
  `}

  ${media.giant`
    max-width: 1140px;
  `}
```

Please, make it configurable.

**Comment by dragma** [comment]
I'm working on it, this feature will have to force the module to get rid of the `phone`, `tablet`, `desktop` and `giant` media queries.

Major release incoming!

**Comment by peterlazzarino** [comment]
@dragma why remove the abstraction if the underlying numbers are made to be configurable? Is it tied to this issue in particular or part of a bigger overhaul?

**Comment by dragma** [comment]
Working on this issue made me realize that this module had a fundamental problem, and it is directly linked to thos aliases `sm` => `phone`

Until now, "aliases" like `desktop` for `lg` weren't really aliases.
There was two entries with the same values. 

Ex :
```javascript
const breakpoints = {
  lg: 1234,
  desktop: 1234,
}
```

So, until then, when you update breakpoints yourselves with GridThemeProvider, you could do weird things like this :
```javascript 
const theme = {
  breakpoints: {
    lg: 1234,
    desktop: 4321,
  }
}
```

I have to find a way to "declare" aliases that are specifically bound to normalized breakpoints. :)
If I can do this, there will not be breaking changes in the usage anymore !

**Comment by dragma** [comment]
v1.2.0 published
