### ISSUE TITLE
Basic example is broken

### ISSUE THREAD

**Issue by Fhou** [dragma/styled-bootstrap-grid#35]
https://github.com/dragma/styled-bootstrap-grid#basics

When I setup a basic example (without `GridThemeProvider`), I get an error

> `Uncaught TypeError: Cannot read property 'getContainerMaxWidth' of undefined at Container.js:45`

It works when I wrap the `Container` in a `GridThemeProvider`.

**Comment by nicolaschenet** [comment]
👍

**Comment by dragma** [comment]
1.2.2 published
