### ISSUE TITLE
Include typescript declaration

### ISSUE THREAD

**Issue by bitworking** [dragma/styled-bootstrap-grid#40]
Hey, thanks for the library. Looks very good. Have you already make a pull request to @types?
Else why not include the declaration file in your package?

**Comment by dragma** [comment]
Since v2.0.x launches few minutes ago, there is a [indes.d.ts](https://github.com/dragma/styled-bootstrap-grid/blob/master/index.d.ts) file thanks to @hector-del-rio !

**Comment by bitworking** [comment]
Haha..nice :) This was fast..thanks!
