### ISSUE TITLE
Feature Request: Get current breakpoint

### ISSUE THREAD

**Issue by checkonetwo** [dragma/styled-bootstrap-grid#41]
Hello and thank you for your lib!

My problem that i need to activate some JS components only on some breakpoints.
Could you add class with current breakpoint (like media) for importing from styled-bootstrap-grid component?

Thank you for answer!

**Comment by dragma** [comment]
Media is already exposed !

Try this !

```javascript
import { media } from 'styled-bootstrap-grid';
import styled from 'styled-components';

const MyComponent = styled.div`
  ${media.xl`
    display: none;
  `}
`;

export default MyComponent;
```

**Comment by checkonetwo** [comment]
I mean something like:

`
{ currentBreakpoint === 'md' ? <SomeComponent /> : null }
`

**Comment by dragma** [comment]
This is not possible for you to think that way.
Bootstrap layout css is made so you can hide or show or resize things depending on your browser resolution.
styled-component is a library that mostly generates css code, and inject it in the dom.

Maybe you should rethink your component so it adapts its design to the given breakpoints.

Example :
```javascript
import React from 'react';
import styled from 'styled-components';
import { media } from 'styled-bootstrap-grid';

const Comp = styled.div`
  display: none;
  ${media.md` // larger than 'md' breakpoint
    display: initial;
  `}
  ${media.lg` // larger than 'lg' breakpoint
    display: none;
  `}
`;

const SomeComponent = props => (
  <div>
    <Comp>Hide if not md</Comp>
  </div>
);

export default SomeComponent;
```

**Comment by checkonetwo** [comment]
Thank you anyway! I will try to do it by my self
Thread could be close

**Comment by kopax** [comment]
I would recommend to use bootstrap-styled:

- For building package: http://bootstrap-styled.github.io/bootstrap-styled
- Bootstrap 4 styled implementation: http://bootstrap-styled.github.io/v4

We have a similar implementation of `withWidth` as material-ui:

```js
import withWidth from 'bootstrap-styled/lib/withWidth';

export default withWidth({ logging: true })(MyComponent);
```

It should also work with this package, as long as you have `theme['$grid-breakpoints´]` in your theme.

**Comment by andreibexa** [comment]
My approach to get current/active breakpoints in Material UI:

```
import { useMediaQuery } from '@material-ui/core';
import { useTheme } from '@material-ui/core/styles';

export default function BreakPoints() {
    const theme = useTheme();

    const activeBreakPoints = theme.breakpoints.keys.filter((breakpoint) =>
        useMediaQuery(theme.breakpoints.up(breakpoint))
    );

    return activeBreakPoints;
}
```


Then, in your other component:


```
import ActiveBreakPoints from './ActiveBreakPoints';

export default function Layout({ children }) {
    const activeBreakPoints = ActiveBreakPoints().join(); // no need to setState on resize, it already changing on resize
    return (
        <div className={activeBreakPoints}>
            <main>{children}</main>
        </div>
    );
}
```
