### ISSUE TITLE
Bug: Typescript support issues

### ISSUE THREAD

**Issue by alexsyo** [dragma/styled-bootstrap-grid#42]
I get `An index signature parameter type cannot be a union type. Consider using a mapped object type instead.` when trying to use this library with typescript.

Apparently, the issue is coming from the labels in the index.d.ts file for the media object (line 119).
Here there is a discussion about this --> https://github.com/Microsoft/TypeScript/issues/24220

Is it just me or am I missing something in the configuration?

**Comment by dragma** [comment]
This is a mission for @hector-del-rio  ! :)

**Comment by hector-del-rio** [comment]
Which version of TypeScript are you using?

**Comment by hector-del-rio** [comment]
I believe #43 will fix this.

**Comment by alexsyo** [comment]
TypeScript 3.2.1.
Yes I think that PR fixes it, Thank you!

**Comment by zaguiini** [comment]
I still got the error.

Typescript version: 3.2.2
`styled-bootstra-grid` version: 2.0.1

**Comment by dragma** [comment]
New version is comming this weekend !

**Comment by dragma** [comment]
I released V3 today. Tell me if this resolves your problem ! :)
