### ISSUE TITLE
Wrong data-name on hiddenMdDown/Up, hiddenLgDown/Up, hiddenXlDown/Up

### ISSUE THREAD

**Issue by vmarchesin** [dragma/styled-bootstrap-grid#46]
The problem is in [this file](https://github.com/dragma/styled-bootstrap-grid/blob/master/src/components/Col/getDataName.ts), on lines 38, 39, 47, 48, 56, 57.

```
38 p.hiddenMdDown && `hidden-xs-down`,
39 p.hiddenMdUp && `hidden-xs-up`,
...
47  p.hiddenLgDown && `hidden-xs-down`,
48 p.hiddenLgUp && `hidden-xs-up`,
...
56 p.hiddenXlDown && `hidden-xs-down`,
57 p.hiddenXlUp && `hidden-xs-up`,
```

I'm not sure how this affects the code elsewhere, but from a quick glance I can see that the `data-names` are incorrect. The correct `data-names` should correctly reflect the `Md`, `Lg` and `Xl` properties instead of referencing `xs` all the time.

I could create a PR for this but I'm not sure if this is enough to solve the problem. Anyone care to elaborate?

**Comment by dragma** [comment]
Thanks for the issue. It will be corrected in the next version :)
