### ISSUE TITLE
Bug: <BaseCSS /> generates error while being used with CRA and Jest

### ISSUE THREAD

**Issue by Jipperism** [dragma/styled-bootstrap-grid#47]
Steps to reproduce:

```
npx create-react-app baseCssTest
cd baseCssTest
yarn add styled-components styled-bootstrap-grid
<edit App.js to include <BaseCSS /> at root level>
yarn test
```

Tests do pass but a very long error about `createStyleSheet` is being shown in console.

**Comment by dragma** [comment]
I realy don't know what causes this. I don't have any time right now to work on this, but i'll try on next monday. 
Stay tuned ! :)

**Comment by DavidHe1127** [comment]
Same issue here as well

**Comment by DavidHe1127** [comment]
Same issue here as well

**Comment by DavidHe1127** [comment]
The problem seems `createGlobalStyle` does not like vendor code.

```
createGlobalStyle`
  @-ms-viewport {
    width: device-width;
  }
`;
```

**Comment by DavidHe1127** [comment]
@dragma I think you need to remove that vendor prefix since `styled-component` your library uses already handles vendor prefix code.
