### ISSUE TITLE
Container Fluid max-width

### ISSUE THREAD

**Issue by dongepulango** [dragma/styled-bootstrap-grid#51]
Is there a way to set `max-width` for `<Container fluid>`?
If not, it would be nice to have an option. 
Thanks

**Comment by dragma** [comment]
You can do this in a higher div. Container fluid will adapt its width to this div.And I do not think setting max width to container fluid is Twitter bootstrap compliant.Le 11 mars 2019 21:00, Don Gepulango <notifications@github.com> a écrit :Is there a way to set max-width for <Container fluid>?
If not, it would be nice to have an option.
Thanks

**Comment by dongepulango** [comment]
Make sense, thank you.
