### ISSUE TITLE
Media min and max

### ISSUE THREAD

**Issue by dongepulango** [dragma/styled-bootstrap-grid#52]
Would be nice to have media as
```
xs-min
xs-max
sm-min
sm-max
md-min
md-max
lg-min
lg-max
xl-min
xl-max

```
so you can apply styles for example like:
```
${media.lg-min && media.lg-max`
    color: red;
` }
```

**Comment by akonyer** [comment]
I also think this would be a nice feature.

**Comment by dragma** [comment]
I see. I'll think about that :)

**Comment by dragma** [comment]
This feature is already in the package. Should be in the documentation though.

```
${media.min.lg` color: red; `}
```
