### ISSUE TITLE
npm install error v3.0.3

### ISSUE THREAD

**Issue by hepicek** [dragma/styled-bootstrap-grid#55]
Hi,

when I install version 3.0.3

I get the error

npm ERR! path /app/node_modules/styled-bootstrap-grid
       npm ERR! code EISGIT
       npm ERR! git /app/node_modules/styled-bootstrap-grid: Appears to be a git repo or submodule.
       npm ERR! git     /app/node_modules/styled-bootstrap-grid
       npm ERR! git Refusing to remove it. Update manually,
       npm ERR! git or move it out of the way first.

There is .git folder  in node-modules which causes the problem.
Can you remove it please

**Comment by akonyer** [comment]
I'm getting this error as well. Very frustrating. Every time I want to do an npm install of a new package I have to delete this package first.

**Comment by hepicek** [comment]
@dragma are you going to fix it? It is over a month.

**Comment by dragma** [comment]
Hello. I'm unfortunately not available at the moment, I have no access to any computer of any kind, just my phone.You can still send me a PR that I'll enjoy to merge if it fulfills your needs and corrects the bug.Regards.Le 24 juin 2019 19:11, hepicek <notifications@github.com> a écrit :@dragma are you going to fix it? It is over a month.

**Comment by dragma** [comment]
You can find here a clue on what you can do to resolve this bug : https://github.com/APSL/react-native-version-number/pull/24

**Comment by dragma** [comment]
Don't worry guys. The PR has been merged and I'll be able to publish the new version on npm within 24h.

**Comment by flo-wolf** [comment]
Is it up yet? I can't deploy to Heroku because of the git folder, since I am not pushing any node_modules myself to heroku I can't remove the .git manually.

**Comment by dragma** [comment]
Yes it is ;) 

v3.0.4 is out.

Keep me posted if there is any bug since this has not been heavily tested !

**Comment by flo-wolf** [comment]
Seems to work just fine for me, thank you very much! Really enjoying the module. Very streamlined, and custom breakpoints.
