### ISSUE TITLE
Customize the amount of columns

### ISSUE THREAD

**Issue by dariusrosendahl** [dragma/styled-bootstrap-grid#59]
Is there any way to customize the amount of columns your want to use? For example: 24 or even 30?

**Comment by dragma** [comment]
No, this is not possible.
This module use the bootstrap 4 layout css, and it is not build to be that much customisable. 
Sorry !

**Comment by jdwillemse** [comment]
I have this same issue. Is there any prospect of this being added? Bootstrap 4 does have this option
```
$grid-columns: 12 !default;
```
