### ISSUE TITLE
Breakpoint sensitive paddings

### ISSUE THREAD

**Issue by flo-wolf** [dragma/styled-bootstrap-grid#61]
I would like to have different paddings between my rows for each breakpoint.
Currently only a fixed padding for rows/columns/containers can be set, which would require me to use no-gutters or to build my own styled-row-component with media querries to work around this, which seems counter-intuitive. 

Would it be possible to allow something like the following for the gridTheme configuration?

```
    col: {
        padding: {
            xl: 72,
            lg: 72,
            md: 64,
            sm: 32,
            xs: 15,
        },
    },
```

**Comment by thezaff** [comment]
Hey, @flo-wolf. Have you found out any workarounds for this? I need different padding for containers on mobile and desktop screens. How can I do this, except writing media queries in each file where I used container component?

**Comment by dragma** [comment]
Hello !
I'll have leterally no time to work on this case this month.

I suggest you  a workaround so you can deal with it in a easyest way

In a new file called `Col.js` (for example), paste the following code (and update its values).

```javascript
import styled from 'styled-components';
import { media , Col as sbgCol } from 'styled-bootstrap-grid';

export const Col = styled(sbgCol)`
  margin-left: 0px;
  margin-right: 0px;
  
  ${media.sm`
    margin-right: 5px;
    margin-leftt: 5px;
  `}
  ${media.md`
    margin-right: 5px;
    margin-leftt: 5px;
  `}
  ${media.lg`
    margin-right: 5px;
    margin-leftt: 5px;
  `}
  ${media.xl`
    margin-right: 5px;
    margin-leftt: 5px;
  `}
`;
```
Now you can import `Col` from this file and the media queries will override the default css.
