### ISSUE TITLE
Usage of !important for components styling causes error on AMP pages. 

### ISSUE THREAD

**Issue by hoshomoh** [dragma/styled-bootstrap-grid#66]
I tried using this package for an AMP page and noticed that I was getting errors related to the usage of `!important` in my styles. After doing some research I found out this was because the package uses `!important` for some of its stylings as you can see [here](https://github.com/dragma/styled-bootstrap-grid/blob/master/src/components/Col/css.ts#L155)

Question:

1. Is there any specific reason why `!important` is used in these cases?
2. Is there a workaround for this?

**Comment by dragma** [comment]
Hello !

I must first say that the CSS used comes directly from the boostrap's CSS. So I do not know if it is really needed or not.

In my opinion there is no workaround. I could see what is new in the new bootstrap CSS version.

Could you come me an example of you are trying to achieve?

**Comment by hoshomoh** [comment]
I am using styled-bootstrap-grid with NextJs, and it is important that I am able to serve the [AMP](https://amp.dev/)  version of my pages which [NextJs](https://nextjs.org/docs#amp-support) support out of the box. AMP however as some strict rules that need to be followed; like not using `!important` in your CSS.

**Comment by hoshomoh** [comment]
Also, I think Boostrap uses `!important` to force specificity, but since this project uses styled-components, we can achieve the same thing without using `!important`. See https://www.styled-components.com/docs/faqs#how-can-i-override-styles-with-higher-specificity

**Comment by dragma** [comment]
I see. And I think you are right !
I'll create a branch for you especially to test this feature. You'll be able to install it with yarn or npm.
If it is concluant and with your feedbacks, I'll upgrade the module ! ;)
This should be done by Monday.

**Comment by hoshomoh** [comment]
Hello, @dragma any luck with this?

**Comment by dragma** [comment]
@hoshomoh 
`npm i -S git+https://github.com/dragma/styled-bootstrap-grid.git\#css-updates`
or
`yarn add git@github.com:dragma/styled-bootstrap-grid.git#css-updates`

Merry christmas !

**Comment by hoshomoh** [comment]
Thanks, mate. 

I Will test this out and let you know if nothing is broken so we can get it into the master branch.

Compliment of the Season.

**Comment by hoshomoh** [comment]
I tried installing using `npm i -S git+https://github.com/dragma/styled-bootstrap-grid.git\#css-updates` and I noticed the command itself works but the folder is empty when I inspect the `node_modules` directory.

**Comment by hoshomoh** [comment]
After doing some research, it seems like it has to be published to `npm` before I can install it. So I forked and published the `css-updates` branch to `npm` https://www.npmjs.com/package/@hoshomoh/styled-bootstrap-grid

I will do some testing to see if I notice any breaking styles.

**Comment by hoshomoh** [comment]
After testing, everything works as expected. If you want you can merge this to the master branch. Until then I will continue using my own fork.
